### ISSUE TITLE
crash after starting yuzu emulator

### ISSUE THREAD

**Issue by cipitaua** [v1993/linuxmotehook#7] opened 2021-04-14 10:18 UTC
I'd like to use wiimote in yuzu switch emulator, which listens to any Cemuhook compatible UDP input source to provide motion and touch input. However, as soon as I start yuzu, the mail.lua crashes:

```
$ ./main.lua 
Note: using individual calibration values
WiiMote successfully registered (MAC 0x0005057E0306)
**
Lgi:ERROR:lgi/marshal.c:1177:lgi_marshal_2c_caller_alloc: assertion failed: (size > 0)
Bail out! Lgi:ERROR:lgi/marshal.c:1177:lgi_marshal_2c_caller_alloc: assertion failed: (size > 0)
Aborted (core dumped)
```

**Comment by v1993** [comment] 2021-04-14 13:16
Closing as duplicate of #5. Please follow discussion there.

**Closed as completed by v1993** 2021-04-14 13:16 UTC
Labels: duplicate
